In [5]:
# Exercise 1
import numpy as np

arr = np.arange(1, 11)

reshaped_arr = arr.reshape(2, 5)
print(reshaped_arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
# Exercise 2
arr_2 = np.arange(1, 21)

extracted_elements = arr_2[5:15]
print(extracted_elements)


[ 6  7  8  9 10 11 12 13 14 15]


In [9]:
# Exercise 3
import pandas as pd

fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

fruits['pears'] = 4
print(fruits)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [11]:
# Exercise 4
data = {
    'name': ['Anu', 'Binu', 'Achu', 'Simi', 'Eva', 'Meenu', 'Aysha', 'Hila', 'Aleena', 'Tovi'],
    'age': [25, 30, 35, 40, 22, 28, 33, 45, 26, 38],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'F', 'M']
}

df = pd.DataFrame(data)
print(df)

     name  age gender
0     Anu   25      F
1    Binu   30      M
2    Achu   35      M
3    Simi   40      M
4     Eva   22      F
5   Meenu   28      M
6   Aysha   33      F
7    Hila   45      F
8  Aleena   26      F
9    Tovi   38      M


In [13]:
# Exercise 5
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Manager', 'Programmer', 
                     'Analyst', 'Manager', 'Programmer', 'Analyst', 'Manager']
print(df)

     name  age gender  occupation
0     Anu   25      F  Programmer
1    Binu   30      M     Manager
2    Achu   35      M     Analyst
3    Simi   40      M     Manager
4     Eva   22      F  Programmer
5   Meenu   28      M     Analyst
6   Aysha   33      F     Manager
7    Hila   45      F  Programmer
8  Aleena   26      F     Analyst
9    Tovi   38      M     Manager


In [15]:
# Exercise 6
df_age_30 = df[df['age'] >= 30]
print(df_age_30)

    name  age gender  occupation
1   Binu   30      M     Manager
2   Achu   35      M     Analyst
3   Simi   40      M     Manager
6  Aysha   33      F     Manager
7   Hila   45      F  Programmer
9   Tovi   38      M     Manager


In [17]:
# Exercise 7
df.to_csv('data.csv', index=False)

df_from_csv = pd.read_csv('data.csv')
print(df_from_csv)

     name  age gender  occupation
0     Anu   25      F  Programmer
1    Binu   30      M     Manager
2    Achu   35      M     Analyst
3    Simi   40      M     Manager
4     Eva   22      F  Programmer
5   Meenu   28      M     Analyst
6   Aysha   33      F     Manager
7    Hila   45      F  Programmer
8  Aleena   26      F     Analyst
9    Tovi   38      M     Manager
